@base_url = {{AUTH0_AUDIENCE}}/users

// Get access token
# @name getAccessToken
POST https://{{AUTH0_DOMAIN}}/oauth/token HTTP/1.1
Content-Type: application/json

{
    "client_id": "{{AUTH0_CLIENT_ID}}",
    "client_secret": "{{AUTH0_CLIENT_SECRET}}",
    "audience": "{{AUTH0_AUDIENCE}}",
    "grant_type": "client_credentials"
}

###

@access_token = {{getAccessToken.response.body.access_token}}
# @access_token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkoyZUNvODNfNXhsalR1dnM5Y3VyZCJ9.eyJodHRwczovL2xvY2FsaG9zdDo2MDk5L3JvbGVzL3JvbGVzIjpbImNvYWNoIl0sImlzcyI6Imh0dHBzOi8vZGV2LWNwZDZhcm1hODAzODZpNXIudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY5MGE2M2E5YjkwNjBiNGVmOTQyNWM5MyIsImF1ZCI6WyJodHRwczovL2xvY2FsaG9zdDo3NTg1IiwiaHR0cHM6Ly9kZXYtY3BkNmFybWE4MDM4Nmk1ci51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYyNjkwOTA2LCJleHAiOjE3NjI3NzczMDYsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MiLCJhenAiOiJjTUpSOWZKR3JTWlY2ZWhJdWszNXBubE5ZbFppOWxxWSIsInBlcm1pc3Npb25zIjpbXX0.kPiQ_oeY0TQX68AUExRMO2dKL6u32mfT7wPPxFexDqkZWskJxbzdbTmjXBHHcUbIEYTkK_KnTwWH_a1q7eKLmqe4-dPAXgpgjF1Tzp-KVqfB2FjAyGCuk1W3_kxVFGC_sCwZtsy2rd6IVkKxqTwVQ-uqRQFshodpra8L_XBu76gSNWCXmrXU06Ev4JlTXei2UEIZymz1zw12uQjinzXSOV_xzkCWhDkFwj0IpJ_kxoy6RKY__v-WY02zNPH1XZ6Nn8-0fntit4YoetuiG4DKujENnLkgX2lq79kpn9UxUfkbdxSQgi9Xm8esTCVbHQ9D_qZM7Lj3rjjQLWm2ksQy9Q

# GetUserByEmail
@email = leewright76@hotmail.com
GET {{base_url}}/{{email}}
Authorization: Bearer {{access_token}}
###

# GetTestToken
GET {{base_url}}/testtoken
Authorization: Bearer {{access_token}}
###
# config
GET {{base_url}}/config
###

# Onboard coach
POST {{base_url}}/me/onboarding
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkoyZUNvODNfNXhsalR1dnM5Y3VyZCJ9.eyJodHRwczovL2xvY2FsaG9zdDo2MDk5L3JvbGVzL3JvbGVzIjpbImNvYWNoIl0sImlzcyI6Imh0dHBzOi8vZGV2LWNwZDZhcm1hODAzODZpNXIudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY5MGE2M2E5YjkwNjBiNGVmOTQyNWM5MyIsImF1ZCI6WyJodHRwczovL2xvY2FsaG9zdDo3NTg1IiwiaHR0cHM6Ly9kZXYtY3BkNmFybWE4MDM4Nmk1ci51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYyNjkwOTA2LCJleHAiOjE3NjI3NzczMDYsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgb2ZmbGluZV9hY2Nlc3MiLCJhenAiOiJjTUpSOWZKR3JTWlY2ZWhJdWszNXBubE5ZbFppOWxxWSIsInBlcm1pc3Npb25zIjpbXX0.kPiQ_oeY0TQX68AUExRMO2dKL6u32mfT7wPPxFexDqkZWskJxbzdbTmjXBHHcUbIEYTkK_KnTwWH_a1q7eKLmqe4-dPAXgpgjF1Tzp-KVqfB2FjAyGCuk1W3_kxVFGC_sCwZtsy2rd6IVkKxqTwVQ-uqRQFshodpra8L_XBu76gSNWCXmrXU06Ev4JlTXei2UEIZymz1zw12uQjinzXSOV_xzkCWhDkFwj0IpJ_kxoy6RKY__v-WY02zNPH1XZ6Nn8-0fntit4YoetuiG4DKujENnLkgX2lq79kpn9UxUfkbdxSQgi9Xm8esTCVbHQ9D_qZM7Lj3rjjQLWm2ksQy9Q
Content-Type: application/json

{
    "email":"lee+coach@dotanddashconsulting.com",
    "fullName":"coach",
    "doB":"1976-03-10",
    "role":"coach",
    "favoriteColor":"pink",
    "address":"apt 8",
    "experience":"10"
}

###

# GetCurrentUser
GET {{base_url}}/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkoyZUNvODNfNXhsalR1dnM5Y3VyZCJ9.eyJodHRwczovL3Byb2plY3RicmFpbi5hcHAvcm9sZXMiOlsidXNlciJdLCJpc3MiOiJodHRwczovL2Rldi1jcGQ2YXJtYTgwMzg2aTVyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ3aW5kb3dzbGl2ZXw2YzFlZjFkNDE1OGUwYTliIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0Ojc1ODUiLCJodHRwczovL2Rldi1jcGQ2YXJtYTgwMzg2aTVyLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3NjMyMjU4MTcsImV4cCI6MTc2MzMxMjIxNywic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBvZmZsaW5lX2FjY2VzcyIsImF6cCI6ImNNSlI5ZkpHclNaVjZlaEl1azM1cG5sTllsWmk5bHFZIiwicGVybWlzc2lvbnMiOltdfQ.B-ys_P5hSgrSk5l75wT6jsLXitlqUwYtwKMIPl_DELjmWE185NMRUfNN-_pLyGVSi6XARbnY98q8I8rCYoWcoqVzpHdIc0hjFbWVUdJYvH0ZhnLujy02S6AbCHXiz_RpViZ4pnQsN3FxetB53EMopMsQi5a3wXamKft76pzW__FiTHTlJL4YAPXPDru93Wh8kwmyoeZyjX4IgF4DjXWBWokiPp1CApQtG5IYrhSHe2U8nAexWgax3Jaqgls0mSDChZ8JRqLZHEvtiAFxLXJQDePln-0CD4YX-W4V4CBJ9X8BpIeCpAOB-eSd0Dg58jkDxZnJCEB35RM8Tr6Or12Exg
# {{access_token}}
###


# GetCurrentUserRoles
GET {{base_url}}/roles
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkoyZUNvODNfNXhsalR1dnM5Y3VyZCJ9.eyJodHRwczovL3Byb2plY3RicmFpbi5hcHAvcm9sZXMiOlsidXNlciJdLCJpc3MiOiJodHRwczovL2Rldi1jcGQ2YXJtYTgwMzg2aTVyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ3aW5kb3dzbGl2ZXw2YzFlZjFkNDE1OGUwYTliIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0Ojc1ODUiLCJodHRwczovL2Rldi1jcGQ2YXJtYTgwMzg2aTVyLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3NjMyMjU4MTcsImV4cCI6MTc2MzMxMjIxNywic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBvZmZsaW5lX2FjY2VzcyIsImF6cCI6ImNNSlI5ZkpHclNaVjZlaEl1azM1cG5sTllsWmk5bHFZIiwicGVybWlzc2lvbnMiOltdfQ.B-ys_P5hSgrSk5l75wT6jsLXitlqUwYtwKMIPl_DELjmWE185NMRUfNN-_pLyGVSi6XARbnY98q8I8rCYoWcoqVzpHdIc0hjFbWVUdJYvH0ZhnLujy02S6AbCHXiz_RpViZ4pnQsN3FxetB53EMopMsQi5a3wXamKft76pzW__FiTHTlJL4YAPXPDru93Wh8kwmyoeZyjX4IgF4DjXWBWokiPp1CApQtG5IYrhSHe2U8nAexWgax3Jaqgls0mSDChZ8JRqLZHEvtiAFxLXJQDePln-0CD4YX-W4V4CBJ9X8BpIeCpAOB-eSd0Dg58jkDxZnJCEB35RM8Tr6Or12Exg
###

# UpdateUserRoles
PUT {{AUTH0_AUDIENCE}}/usermanagement/windowslive%7C6c1ef1d4158e0a9b/roles
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkoyZUNvODNfNXhsalR1dnM5Y3VyZCJ9.eyJodHRwczovL3Byb2plY3RicmFpbi5hcHAvcm9sZXMiOlsiYWRtaW4iLCJjb2FjaCJdLCJpc3MiOiJodHRwczovL2Rldi1jcGQ2YXJtYTgwMzg2aTVyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2OTIzNGY4NDg3ODQyZjQxN2IxMDg4ZjAiLCJhdWQiOlsiaHR0cHM6Ly9sb2NhbGhvc3Q6NzU4NSIsImh0dHBzOi8vZGV2LWNwZDZhcm1hODAzODZpNXIudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTc2NDE3NDQ0NSwiZXhwIjoxNzY0MjYwODQ1LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIiwiYXpwIjoiY01KUjlmSkdyU1pWNmVoSXVrMzVwbmxOWWxaaTlscVkiLCJwZXJtaXNzaW9ucyI6W119.Iy9N96WeGlBQGPw7xbs1ZKHdVTuVAti4Rvk5MpmmO0zz2B3c-q0gy3q9MJ2t3ubTV-cOETRrP3m-OoK_wYM5p-9mEt4IWD1KptFQ_fZF3xx3f3gqEhKrimcpMV6NJNV5z2Ej8gbdcaWjPt1n5J2BIiq6gOQLbM7vYlzMM6ykfstXQAv9hkQ7Bxar7ZqNRIqggFJn2MkA8D9nIKyP_wY-Mrm26yZMsCi9uGse_7kjmXkhUzcagV8V_hZ1gROMs4aOryFifCkIy4dD2We7Te93LECf8QvY39-N42XFpDvAkEsxE3yKs7Vx2xUrOwgut3abD651qQi5Qnja40BvGL1MlQ
Content-Type: application/json

{
    "roles": ["test"]
}
###