<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ProjectBrain.Api.Tests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectBrain.Database\ProjectBrain.Database.csproj" />
    <ProjectReference Include="..\ProjectBrain.Domain\ProjectBrain.Domain.csproj" />
    <ProjectReference Include="..\ProjectBrain.Shared.Dtos\ProjectBrain.Shared.Dtos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Auth0.AuthenticationApi" Version="7.46.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.7.0" />
  </ItemGroup>

</Project>
