# Run when commits are pushed to main
on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - main

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_CERTIFICATE_NAME_API: ${{ vars.AZURE_CERTIFICATE_NAME_API }}
      AZURE_CUSTOM_DOMAIN_API: ${{ vars.AZURE_CUSTOM_DOMAIN_API }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_MIN_REPLICAS: ${{ vars.AZURE_MIN_REPLICAS }}
      AZURE_CERTIFICATE_NAME_APP: ${{ vars.AZURE_CERTIFICATE_NAME_APP }}
      AZURE_CUSTOM_DOMAIN_APP: ${{ vars.AZURE_CUSTOM_DOMAIN_APP }}
      AZURE_DEPLOYMENT_ENVIRONMENT: ${{ vars.AZURE_DEPLOYMENT_ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install azd
        uses: Azure/setup-azd@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.x
            9.x
            10.x

      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh


      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZURE_CACHE_PASSWORD: ${{ secrets.AZURE_CACHE_PASSWORD }}
          AZURE_LAUNCHDARKLY_SDK_KEY: ${{ secrets.AZURE_LAUNCHDARKLY_SDK_KEY }}
          AZURE_MAILGUN_DOMAIN: ${{ secrets.AZURE_MAILGUN_DOMAIN }}
          AZURE_PROJECTBRAIN_PASSWORD: ${{ secrets.AZURE_PROJECTBRAIN_PASSWORD }}
          AZURE_ADMIN_USER_PASSWORD: ${{ secrets.AZURE_ADMIN_USER_PASSWORD }}
          AZURE_AUTH0_CLIENTID: ${{ secrets.AZURE_AUTH0_CLIENTID }}
          AZURE_GOOGLE_MAPS_GEOCODING_API_KEY: ${{ secrets.AZURE_GOOGLE_MAPS_GEOCODING_API_KEY }}
          AZURE_AUTH0_DOMAIN: ${{ secrets.AZURE_AUTH0_DOMAIN }}
          AZURE_AUTH0_WEBHOOK_TOKEN: ${{ secrets.AZURE_AUTH0_WEBHOOK_TOKEN }}
          AZURE_FIREBASE_CREDENTIALS_JSON: ${{ secrets.AZURE_FIREBASE_CREDENTIALS_JSON }}
          AZURE_MAILGUN_API_KEY: ${{ secrets.AZURE_MAILGUN_API_KEY }}
          AZURE_AUTH0_MANAGEMENTAPICLIENTID: ${{ secrets.AZURE_AUTH0_MANAGEMENTAPICLIENTID }}
          AZURE_AUTH0_MANAGEMENTAPICLIENTSECRET: ${{ secrets.AZURE_AUTH0_MANAGEMENTAPICLIENTSECRET }}

      - name: Deploy Application
        run: azd deploy --no-prompt
        env:
          AZURE_CACHE_PASSWORD: ${{ secrets.AZURE_CACHE_PASSWORD }}
          AZURE_LAUNCHDARKLY_SDK_KEY: ${{ secrets.AZURE_LAUNCHDARKLY_SDK_KEY }}
          AZURE_MAILGUN_DOMAIN: ${{ secrets.AZURE_MAILGUN_DOMAIN }}
          AZURE_PROJECTBRAIN_PASSWORD: ${{ secrets.AZURE_PROJECTBRAIN_PASSWORD }}
          AZURE_ADMIN_USER_PASSWORD: ${{ secrets.AZURE_ADMIN_USER_PASSWORD }}
          AZURE_AUTH0_CLIENTID: ${{ secrets.AZURE_AUTH0_CLIENTID }}
          AZURE_GOOGLE_MAPS_GEOCODING_API_KEY: ${{ secrets.AZURE_GOOGLE_MAPS_GEOCODING_API_KEY }}
          AZURE_AUTH0_DOMAIN: ${{ secrets.AZURE_AUTH0_DOMAIN }}
          AZURE_AUTH0_WEBHOOK_TOKEN: ${{ secrets.AZURE_AUTH0_WEBHOOK_TOKEN }}
          AZURE_FIREBASE_CREDENTIALS_JSON: ${{ secrets.AZURE_FIREBASE_CREDENTIALS_JSON }}
          AZURE_MAILGUN_API_KEY: ${{ secrets.AZURE_MAILGUN_API_KEY }}
          AZURE_AUTH0_MANAGEMENTAPICLIENTID: ${{ secrets.AZURE_AUTH0_MANAGEMENTAPICLIENTID }}
          AZURE_AUTH0_MANAGEMENTAPICLIENTSECRET: ${{ secrets.AZURE_AUTH0_MANAGEMENTAPICLIENTSECRET }}
        
