name: Deploy (staging)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: tests
    uses: ./.github/workflows/azure-deploy.yml
    with:
      deploy_environment: staging
    secrets: inherit

  scale:
    needs: deploy
    uses: ./.github/workflows/scale-staging-container-apps.yml
    secrets: inherit
