name: Deploy (production)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  
jobs:
  deploy:
    uses: ./.github/workflows/azure-deploy.yml
    with:
      deploy_environment: production
    secrets: inherit
